import { chromium } from 'playwright';
const [url, out] = process.argv.slice(2);
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1440, height: 780 }, deviceScaleFactor: 2 });
const p = await c.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto(url, { waitUntil: 'networkidle' });
await p.evaluate(() => document.fonts.ready);
await p.waitForTimeout(500);
await p.getByRole('button', { name: /^Display/ }).click();
await p.waitForTimeout(500);
const labels = await p.locator('[class*="dm__label"]').allInnerTexts();
const pills = await p.locator('[class*="dm__pill"]').allInnerTexts();
console.log('rows:', labels.join(' | '));
console.log('field pills:', pills.join(' | '));
console.log('errors:', errs.length);
for (const e of [...new Set(errs)].slice(0,2)) console.log('  ' + e.slice(0,120));
await p.screenshot({ path: out });
console.log('shot', out);
await b.close();
