/* GENERATED by tools/gen-proto-themes.mjs - do not edit by hand.
 *
 * The same variants as proto-themes.css, resolved for antd. The CSS file is what
 * the app's own rules read; this is what ConfigProvider needs, because antd
 * derives hover/active/border ramps from colorPrimary with a palette algorithm
 * that cannot read a CSS custom property - hand it a var() and the whole ramp
 * silently falls back to black. Switching a colour in the panel therefore has to
 * write BOTH layers or half the screen moves and the other half does not.
 */
/* antd is handed a real font-family string for the same reason it is handed real
   hexes: its components carry their own font-family, written from antd's own
   fontFamily theme token, so the CSS variable never reaches them. Switch only
   the variable and the body font changes while every table, tab, input and
   button on the page stays on the old face - which is most of the page. */
export interface ProtoFont {
  label: string;
  note: string;
  /** The five roles a pairing sets. See gen-proto-themes.mjs for what each one
   *  is for, and why the tag is a role rather than "whatever the mono is". */
  sans: string;
  mono: string;
  display: string;
  prose: string;
  tag: string;
  num: string;
  /** How the title and the tags are SET, not just which face they use. The
   *  prototype panel renders a specimen of each system from these, so the
   *  dropdown shows the difference instead of naming it. */
  displayWeight: number;
  displayTracking: string;
  tagCase: string;
  tagTracking: string;
  tagSize: string;
  tagWeight: number;
}

export interface ProtoVariant {
  label: string;
  /** primitive ramp overrides, for the few places antd is handed a primitive */
  palette: Record<string, string>;
  /** semantic roles, already resolved, per theme */
  light: Record<string, string>;
  dark: Record<string, string>;
}

export const GREYS: Record<string, ProtoVariant> = {
    "cool": {
      "label": "Cool",
      "palette": {
        "n-0": "#ffffff",
        "n-25": "#fafcfd",
        "n-50": "#f6f9fa",
        "n-100": "#f0f3f4",
        "n-150": "#e8eced",
        "n-200": "#dde2e4",
        "n-300": "#c9cfd1",
        "n-400": "#9fa6a8",
        "n-500": "#798285",
        "n-550": "#6a7376",
        "n-600": "#5c6568",
        "n-700": "#41494c",
        "n-800": "#282f32",
        "n-850": "#1e2528",
        "n-900": "#161c1e",
        "n-950": "#090e10",
        "dark-void": "#030506",
        "dark-sunken": "#070c0e",
        "dark-base": "#0f1517",
        "dark-raised": "#1a2023",
        "dark-overlay": "#232a2d",
        "dark-text-hi": "#eff2f4",
        "dark-text-mid": "#b9bfc1",
        "dark-text-lo": "#8f9799"
      },
      "light": {
        "surface-canvas": "#f0f3f4",
        "surface-default": "#ffffff",
        "surface-sunken": "#f6f9fa",
        "surface-raised": "#ffffff",
        "surface-nav": "#f6f9fa",
        "surface-hover": "#f0f3f4",
        "surface-active": "#e8eced",
        "surface-disabled": "#f0f3f4",
        "surface-inverse": "#161c1e",
        "content-primary": "#161c1e",
        "content-secondary": "#41494c",
        "content-muted": "#5c6568",
        "content-placeholder": "#6a7376",
        "content-disabled": "#9fa6a8",
        "content-decorative": "#798285",
        "content-inverse": "#ffffff",
        "border-subtle": "#e8eced",
        "border-default": "#dde2e4",
        "border-strong": "#c9cfd1",
        "action-primary-bg": "#161c1e",
        "action-primary-bg-hover": "#282f32",
        "action-primary-bg-active": "#090e10",
        "action-primary-fg": "#ffffff",
        "action-secondary-bg": "#ffffff",
        "action-secondary-bg-hover": "#f6f9fa",
        "action-secondary-bg-active": "#e8eced",
        "action-secondary-fg": "#282f32",
        "action-secondary-border": "#dde2e4",
        "action-subtle-bg-hover": "#f0f3f4",
        "action-subtle-bg-active": "#e8eced",
        "action-subtle-fg": "#41494c",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#f6f9fa",
        "status-neutral-border": "#dde2e4",
        "status-neutral-fg": "#41494c",
        "impact-low": "#9fa6a8",
        "impact-track": "#dde2e4",
        "focus-ring-offset": "#ffffff"
      },
      "dark": {
        "surface-canvas": "#030506",
        "surface-default": "#0f1517",
        "surface-sunken": "#070c0e",
        "surface-raised": "#1a2023",
        "surface-nav": "#070c0e",
        "surface-hover": "#1a2023",
        "surface-active": "#232a2d",
        "surface-disabled": "#070c0e",
        "surface-inverse": "#f0f3f4",
        "content-primary": "#eff2f4",
        "content-secondary": "#b9bfc1",
        "content-muted": "#8f9799",
        "content-placeholder": "#8f9799",
        "content-disabled": "#5c6568",
        "content-decorative": "#798285",
        "content-inverse": "#090e10",
        "border-subtle": "#1e2528",
        "border-default": "#282f32",
        "border-strong": "#41494c",
        "action-primary-bg": "#f0f3f4",
        "action-primary-bg-hover": "#ffffff",
        "action-primary-bg-active": "#dde2e4",
        "action-primary-fg": "#090e10",
        "action-secondary-bg": "#1a2023",
        "action-secondary-bg-hover": "#232a2d",
        "action-secondary-bg-active": "#070c0e",
        "action-secondary-fg": "#eff2f4",
        "action-secondary-border": "#282f32",
        "action-subtle-bg-hover": "#1a2023",
        "action-subtle-bg-active": "#232a2d",
        "action-subtle-fg": "#b9bfc1",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#1a2023",
        "status-neutral-border": "#282f32",
        "status-neutral-fg": "#b9bfc1",
        "impact-low": "#798285",
        "impact-track": "#282f32",
        "focus-ring-offset": "#0f1517"
      }
    },
    "true": {
      "label": "True",
      "palette": {
        "n-0": "#ffffff",
        "n-25": "#fcfcfc",
        "n-50": "#f8f8f8",
        "n-100": "#f2f2f2",
        "n-150": "#ebebeb",
        "n-200": "#e1e1e1",
        "n-300": "#cecece",
        "n-400": "#a4a4a4",
        "n-500": "#808080",
        "n-550": "#717171",
        "n-600": "#636363",
        "n-700": "#484848",
        "n-800": "#2e2e2e",
        "n-850": "#242424",
        "n-900": "#1b1b1b",
        "n-950": "#0d0d0d",
        "dark-void": "#040404",
        "dark-sunken": "#0b0b0b",
        "dark-base": "#141414",
        "dark-raised": "#1f1f1f",
        "dark-overlay": "#292929",
        "dark-text-hi": "#f2f2f2",
        "dark-text-mid": "#bebebe",
        "dark-text-lo": "#959595"
      },
      "light": {
        "surface-canvas": "#f2f2f2",
        "surface-default": "#ffffff",
        "surface-sunken": "#f8f8f8",
        "surface-raised": "#ffffff",
        "surface-nav": "#f8f8f8",
        "surface-hover": "#f2f2f2",
        "surface-active": "#ebebeb",
        "surface-disabled": "#f2f2f2",
        "surface-inverse": "#1b1b1b",
        "content-primary": "#1b1b1b",
        "content-secondary": "#484848",
        "content-muted": "#636363",
        "content-placeholder": "#717171",
        "content-disabled": "#a4a4a4",
        "content-decorative": "#808080",
        "content-inverse": "#ffffff",
        "border-subtle": "#ebebeb",
        "border-default": "#e1e1e1",
        "border-strong": "#cecece",
        "action-primary-bg": "#1b1b1b",
        "action-primary-bg-hover": "#2e2e2e",
        "action-primary-bg-active": "#0d0d0d",
        "action-primary-fg": "#ffffff",
        "action-secondary-bg": "#ffffff",
        "action-secondary-bg-hover": "#f8f8f8",
        "action-secondary-bg-active": "#ebebeb",
        "action-secondary-fg": "#2e2e2e",
        "action-secondary-border": "#e1e1e1",
        "action-subtle-bg-hover": "#f2f2f2",
        "action-subtle-bg-active": "#ebebeb",
        "action-subtle-fg": "#484848",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#f8f8f8",
        "status-neutral-border": "#e1e1e1",
        "status-neutral-fg": "#484848",
        "impact-low": "#a4a4a4",
        "impact-track": "#e1e1e1",
        "focus-ring-offset": "#ffffff"
      },
      "dark": {
        "surface-canvas": "#040404",
        "surface-default": "#141414",
        "surface-sunken": "#0b0b0b",
        "surface-raised": "#1f1f1f",
        "surface-nav": "#0b0b0b",
        "surface-hover": "#1f1f1f",
        "surface-active": "#292929",
        "surface-disabled": "#0b0b0b",
        "surface-inverse": "#f2f2f2",
        "content-primary": "#f2f2f2",
        "content-secondary": "#bebebe",
        "content-muted": "#959595",
        "content-placeholder": "#959595",
        "content-disabled": "#636363",
        "content-decorative": "#808080",
        "content-inverse": "#0d0d0d",
        "border-subtle": "#242424",
        "border-default": "#2e2e2e",
        "border-strong": "#484848",
        "action-primary-bg": "#f2f2f2",
        "action-primary-bg-hover": "#ffffff",
        "action-primary-bg-active": "#e1e1e1",
        "action-primary-fg": "#0d0d0d",
        "action-secondary-bg": "#1f1f1f",
        "action-secondary-bg-hover": "#292929",
        "action-secondary-bg-active": "#0b0b0b",
        "action-secondary-fg": "#f2f2f2",
        "action-secondary-border": "#2e2e2e",
        "action-subtle-bg-hover": "#1f1f1f",
        "action-subtle-bg-active": "#292929",
        "action-subtle-fg": "#bebebe",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#1f1f1f",
        "status-neutral-border": "#2e2e2e",
        "status-neutral-fg": "#bebebe",
        "impact-low": "#808080",
        "impact-track": "#2e2e2e",
        "focus-ring-offset": "#141414"
      }
    },
    "warm": {
      "label": "Warm",
      "palette": {
        "n-0": "#ffffff",
        "n-25": "#fcfcfa",
        "n-50": "#faf8f6",
        "n-100": "#f4f2ef",
        "n-150": "#edebe7",
        "n-200": "#e4e1dd",
        "n-300": "#d0cdc9",
        "n-400": "#a8a49e",
        "n-500": "#847f79",
        "n-550": "#76716a",
        "n-600": "#67625c",
        "n-700": "#4c4741",
        "n-800": "#312d28",
        "n-850": "#27231e",
        "n-900": "#1d1a16",
        "n-950": "#100d09",
        "dark-void": "#060403",
        "dark-sunken": "#0d0b07",
        "dark-base": "#16130f",
        "dark-raised": "#221f1a",
        "dark-overlay": "#2c2823",
        "dark-text-hi": "#f3f1ef",
        "dark-text-mid": "#c0bdb9",
        "dark-text-lo": "#99948f"
      },
      "light": {
        "surface-canvas": "#f4f2ef",
        "surface-default": "#ffffff",
        "surface-sunken": "#faf8f6",
        "surface-raised": "#ffffff",
        "surface-nav": "#faf8f6",
        "surface-hover": "#f4f2ef",
        "surface-active": "#edebe7",
        "surface-disabled": "#f4f2ef",
        "surface-inverse": "#1d1a16",
        "content-primary": "#1d1a16",
        "content-secondary": "#4c4741",
        "content-muted": "#67625c",
        "content-placeholder": "#76716a",
        "content-disabled": "#a8a49e",
        "content-decorative": "#847f79",
        "content-inverse": "#ffffff",
        "border-subtle": "#edebe7",
        "border-default": "#e4e1dd",
        "border-strong": "#d0cdc9",
        "action-primary-bg": "#1d1a16",
        "action-primary-bg-hover": "#312d28",
        "action-primary-bg-active": "#100d09",
        "action-primary-fg": "#ffffff",
        "action-secondary-bg": "#ffffff",
        "action-secondary-bg-hover": "#faf8f6",
        "action-secondary-bg-active": "#edebe7",
        "action-secondary-fg": "#312d28",
        "action-secondary-border": "#e4e1dd",
        "action-subtle-bg-hover": "#f4f2ef",
        "action-subtle-bg-active": "#edebe7",
        "action-subtle-fg": "#4c4741",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#faf8f6",
        "status-neutral-border": "#e4e1dd",
        "status-neutral-fg": "#4c4741",
        "impact-low": "#a8a49e",
        "impact-track": "#e4e1dd",
        "focus-ring-offset": "#ffffff"
      },
      "dark": {
        "surface-canvas": "#060403",
        "surface-default": "#16130f",
        "surface-sunken": "#0d0b07",
        "surface-raised": "#221f1a",
        "surface-nav": "#0d0b07",
        "surface-hover": "#221f1a",
        "surface-active": "#2c2823",
        "surface-disabled": "#0d0b07",
        "surface-inverse": "#f4f2ef",
        "content-primary": "#f3f1ef",
        "content-secondary": "#c0bdb9",
        "content-muted": "#99948f",
        "content-placeholder": "#99948f",
        "content-disabled": "#67625c",
        "content-decorative": "#847f79",
        "content-inverse": "#100d09",
        "border-subtle": "#27231e",
        "border-default": "#312d28",
        "border-strong": "#4c4741",
        "action-primary-bg": "#f4f2ef",
        "action-primary-bg-hover": "#ffffff",
        "action-primary-bg-active": "#e4e1dd",
        "action-primary-fg": "#100d09",
        "action-secondary-bg": "#221f1a",
        "action-secondary-bg-hover": "#2c2823",
        "action-secondary-bg-active": "#0d0b07",
        "action-secondary-fg": "#f3f1ef",
        "action-secondary-border": "#312d28",
        "action-subtle-bg-hover": "#221f1a",
        "action-subtle-bg-active": "#2c2823",
        "action-subtle-fg": "#c0bdb9",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#221f1a",
        "status-neutral-border": "#312d28",
        "status-neutral-fg": "#c0bdb9",
        "impact-low": "#847f79",
        "impact-track": "#312d28",
        "focus-ring-offset": "#16130f"
      }
    }
  };

export const ACCENTS: Record<string, ProtoVariant> = {
    "teal": {
      "label": "Teal",
      "palette": {
        "a-50": "#e5f5f8",
        "a-100": "#cfedf2",
        "a-200": "#acdbe3",
        "a-300": "#81c0cc",
        "a-400": "#4f99a6",
        "a-500": "#287b88",
        "a-600": "#0d636f",
        "a-700": "#094b55",
        "a-800": "#06373e",
        "a-900": "#022227"
      },
      "light": {
        "surface-selected": "#e5f5f8",
        "content-accent": "#0d636f",
        "border-accent": "#287b88",
        "status-info-bg": "#e5f5f8",
        "status-info-border": "#acdbe3",
        "status-info-fg": "#094b55",
        "focus-ring": "#287b88"
      },
      "dark": {
        "surface-selected": "#022227",
        "content-accent": "#81c0cc",
        "border-accent": "#287b88",
        "status-info-bg": "#022227",
        "status-info-border": "#06373e",
        "status-info-fg": "#acdbe3",
        "focus-ring": "#4f99a6"
      }
    },
    "indigo": {
      "label": "Indigo",
      "palette": {
        "a-50": "#eef1fe",
        "a-100": "#e0e5fc",
        "a-200": "#c7cff3",
        "a-300": "#a7b2df",
        "a-400": "#7e89bb",
        "a-500": "#616b9d",
        "a-600": "#4c5482",
        "a-700": "#393f63",
        "a-800": "#292e4a",
        "a-900": "#181b2f"
      },
      "light": {
        "surface-selected": "#eef1fe",
        "content-accent": "#4c5482",
        "border-accent": "#616b9d",
        "status-info-bg": "#eef1fe",
        "status-info-border": "#c7cff3",
        "status-info-fg": "#393f63",
        "focus-ring": "#616b9d"
      },
      "dark": {
        "surface-selected": "#181b2f",
        "content-accent": "#a7b2df",
        "border-accent": "#616b9d",
        "status-info-bg": "#181b2f",
        "status-info-border": "#292e4a",
        "status-info-fg": "#c7cff3",
        "focus-ring": "#7e89bb"
      }
    }
  };

export const FONTS: Record<string, ProtoFont> = {
    "plex": {
      "label": "Graphite",
      "note": "the shipped voice: one family doing every job, no contrast anywhere",
      "sans": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "mono": "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "display": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "prose": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "tag": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "num": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "displayWeight": 600,
      "displayTracking": "-0.011em",
      "tagCase": "none",
      "tagTracking": "var(--m-tracking-normal)",
      "tagSize": "var(--m-text-xs)",
      "tagWeight": 400
    },
    "swiss": {
      "label": "Swiss",
      "note": "Linear: one grotesque, headings pulled tight, tags as small caps",
      "sans": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "mono": "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "display": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "prose": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "tag": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "num": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "displayWeight": 600,
      "displayTracking": "-0.028em",
      "tagCase": "uppercase",
      "tagTracking": "0.075em",
      "tagSize": "0.625rem",
      "tagWeight": 600
    },
    "console": {
      "label": "Console",
      "note": "Vercel: sans interface, and every figure and tag in the mono",
      "sans": "'Geist', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "mono": "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "display": "'Geist', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "prose": "'Geist', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "tag": "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "num": "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "displayWeight": 600,
      "displayTracking": "-0.032em",
      "tagCase": "uppercase",
      "tagTracking": "0.04em",
      "tagSize": "0.625rem",
      "tagWeight": 500
    },
    "editorial": {
      "label": "Editorial",
      "note": "Notion: a text serif on the page title and the writing, sans rows",
      "sans": "'Source Sans 3', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "mono": "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "display": "'Source Serif 4', Georgia, 'Times New Roman', serif",
      "prose": "'Source Serif 4', Georgia, 'Times New Roman', serif",
      "tag": "'Source Sans 3', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "num": "'Source Sans 3', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "displayWeight": 600,
      "displayTracking": "-0.012em",
      "tagCase": "none",
      "tagTracking": "var(--m-tracking-normal)",
      "tagSize": "var(--m-text-xs)",
      "tagWeight": 400
    },
    "system": {
      "label": "System",
      "note": "GitHub: the OS’s own face, a size up, nothing loaded, nothing foreign",
      "sans": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      "mono": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
      "display": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      "prose": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      "tag": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      "num": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
      "displayWeight": 600,
      "displayTracking": "-0.021em",
      "tagCase": "none",
      "tagTracking": "var(--m-tracking-normal)",
      "tagSize": "var(--m-text-xs)",
      "tagWeight": 400
    }
  };

export const DEFAULTS = { grey: 'cool', accent: 'teal', font: 'plex', density: 'compact' } as const;

export type GreyKey = keyof typeof GREYS;
export type AccentKey = keyof typeof ACCENTS;
export type FontKey = keyof typeof FONTS;
export type DensityKey = 'compact' | 'spaced';
