/* GENERATED by tools/gen-proto-themes.mjs - do not edit by hand.
 *
 * The same variants as proto-themes.css, resolved for antd. The CSS file is what
 * the app's own rules read; this is what ConfigProvider needs, because antd
 * derives hover/active/border ramps from colorPrimary with a palette algorithm
 * that cannot read a CSS custom property - hand it a var() and the whole ramp
 * silently falls back to black. Switching a colour in the panel therefore has to
 * write BOTH layers or half the screen moves and the other half does not.
 */
/* antd is handed a real font-family string for the same reason it is handed real
   hexes: its components carry their own font-family, written from antd's own
   fontFamily theme token, so the CSS variable never reaches them. Switch only
   the variable and the body font changes while every table, tab, input and
   button on the page stays on the old face - which is most of the page. */
export interface ProtoFont {
  label: string;
  note: string;
  /** The five roles a pairing sets. See gen-proto-themes.mjs for what each one
   *  is for, and why the tag is a role rather than "whatever the mono is". */
  sans: string;
  mono: string;
  display: string;
  prose: string;
  tag: string;
  num: string;
  /** How the title and the tags are SET, not just which face they use. The
   *  prototype panel renders a specimen of each system from these, so the
   *  dropdown shows the difference instead of naming it. */
  displayWeight: number;
  displayTracking: string;
  tagCase: string;
  tagTracking: string;
  tagSize: string;
  tagWeight: number;
}

export interface ProtoVariant {
  label: string;
  /** Greys have none; an accent carries how far it sits from the nearest alarm
   *  colour, which is the one fact that can rule a hue out. */
  note?: string;
  /** primitive ramp overrides, for the few places antd is handed a primitive */
  palette: Record<string, string>;
  /** semantic roles, already resolved, per theme */
  light: Record<string, string>;
  dark: Record<string, string>;
}

export const GREYS: Record<string, ProtoVariant> = {
    "cool": {
      "label": "Cool",
      "palette": {
        "n-0": "#ffffff",
        "n-25": "#fafcfd",
        "n-50": "#f6f9fa",
        "n-100": "#f0f3f4",
        "n-150": "#e8eced",
        "n-200": "#dde2e4",
        "n-300": "#c9cfd1",
        "n-400": "#9fa6a8",
        "n-500": "#798285",
        "n-550": "#6a7376",
        "n-600": "#5c6568",
        "n-700": "#41494c",
        "n-800": "#282f32",
        "n-850": "#1e2528",
        "n-900": "#161c1e",
        "n-950": "#090e10",
        "dark-void": "#030506",
        "dark-sunken": "#070c0e",
        "dark-base": "#0f1517",
        "dark-raised": "#1a2023",
        "dark-overlay": "#232a2d",
        "dark-text-hi": "#eff2f4",
        "dark-text-mid": "#b9bfc1",
        "dark-text-lo": "#8f9799"
      },
      "light": {
        "surface-canvas": "#f0f3f4",
        "surface-default": "#ffffff",
        "surface-sunken": "#f6f9fa",
        "surface-raised": "#ffffff",
        "surface-nav": "#f6f9fa",
        "surface-hover": "#f0f3f4",
        "surface-active": "#e8eced",
        "surface-disabled": "#f0f3f4",
        "surface-inverse": "#161c1e",
        "content-primary": "#161c1e",
        "content-secondary": "#41494c",
        "content-muted": "#5c6568",
        "content-placeholder": "#6a7376",
        "content-disabled": "#9fa6a8",
        "content-decorative": "#798285",
        "content-inverse": "#ffffff",
        "border-subtle": "#e8eced",
        "border-default": "#dde2e4",
        "border-strong": "#c9cfd1",
        "action-primary-bg": "#161c1e",
        "action-primary-bg-hover": "#282f32",
        "action-primary-bg-active": "#090e10",
        "action-primary-fg": "#ffffff",
        "action-secondary-bg": "#ffffff",
        "action-secondary-bg-hover": "#f6f9fa",
        "action-secondary-bg-active": "#e8eced",
        "action-secondary-fg": "#282f32",
        "action-secondary-border": "#dde2e4",
        "action-subtle-bg-hover": "#f0f3f4",
        "action-subtle-bg-active": "#e8eced",
        "action-subtle-fg": "#41494c",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#f6f9fa",
        "status-neutral-border": "#dde2e4",
        "status-neutral-fg": "#41494c",
        "impact-low": "#9fa6a8",
        "impact-track": "#dde2e4",
        "focus-ring-offset": "#ffffff"
      },
      "dark": {
        "surface-canvas": "#030506",
        "surface-default": "#0f1517",
        "surface-sunken": "#070c0e",
        "surface-raised": "#1a2023",
        "surface-nav": "#070c0e",
        "surface-hover": "#1a2023",
        "surface-active": "#232a2d",
        "surface-disabled": "#070c0e",
        "surface-inverse": "#f0f3f4",
        "content-primary": "#eff2f4",
        "content-secondary": "#b9bfc1",
        "content-muted": "#8f9799",
        "content-placeholder": "#8f9799",
        "content-disabled": "#5c6568",
        "content-decorative": "#798285",
        "content-inverse": "#090e10",
        "border-subtle": "#1e2528",
        "border-default": "#282f32",
        "border-strong": "#41494c",
        "action-primary-bg": "#f0f3f4",
        "action-primary-bg-hover": "#ffffff",
        "action-primary-bg-active": "#dde2e4",
        "action-primary-fg": "#090e10",
        "action-secondary-bg": "#1a2023",
        "action-secondary-bg-hover": "#232a2d",
        "action-secondary-bg-active": "#070c0e",
        "action-secondary-fg": "#eff2f4",
        "action-secondary-border": "#282f32",
        "action-subtle-bg-hover": "#1a2023",
        "action-subtle-bg-active": "#232a2d",
        "action-subtle-fg": "#b9bfc1",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#1a2023",
        "status-neutral-border": "#282f32",
        "status-neutral-fg": "#b9bfc1",
        "impact-low": "#798285",
        "impact-track": "#282f32",
        "focus-ring-offset": "#0f1517"
      }
    },
    "true": {
      "label": "True",
      "palette": {
        "n-0": "#ffffff",
        "n-25": "#fcfcfc",
        "n-50": "#f8f8f8",
        "n-100": "#f2f2f2",
        "n-150": "#ebebeb",
        "n-200": "#e1e1e1",
        "n-300": "#cecece",
        "n-400": "#a4a4a4",
        "n-500": "#808080",
        "n-550": "#717171",
        "n-600": "#636363",
        "n-700": "#484848",
        "n-800": "#2e2e2e",
        "n-850": "#242424",
        "n-900": "#1b1b1b",
        "n-950": "#0d0d0d",
        "dark-void": "#040404",
        "dark-sunken": "#0b0b0b",
        "dark-base": "#141414",
        "dark-raised": "#1f1f1f",
        "dark-overlay": "#292929",
        "dark-text-hi": "#f2f2f2",
        "dark-text-mid": "#bebebe",
        "dark-text-lo": "#959595"
      },
      "light": {
        "surface-canvas": "#f2f2f2",
        "surface-default": "#ffffff",
        "surface-sunken": "#f8f8f8",
        "surface-raised": "#ffffff",
        "surface-nav": "#f8f8f8",
        "surface-hover": "#f2f2f2",
        "surface-active": "#ebebeb",
        "surface-disabled": "#f2f2f2",
        "surface-inverse": "#1b1b1b",
        "content-primary": "#1b1b1b",
        "content-secondary": "#484848",
        "content-muted": "#636363",
        "content-placeholder": "#717171",
        "content-disabled": "#a4a4a4",
        "content-decorative": "#808080",
        "content-inverse": "#ffffff",
        "border-subtle": "#ebebeb",
        "border-default": "#e1e1e1",
        "border-strong": "#cecece",
        "action-primary-bg": "#1b1b1b",
        "action-primary-bg-hover": "#2e2e2e",
        "action-primary-bg-active": "#0d0d0d",
        "action-primary-fg": "#ffffff",
        "action-secondary-bg": "#ffffff",
        "action-secondary-bg-hover": "#f8f8f8",
        "action-secondary-bg-active": "#ebebeb",
        "action-secondary-fg": "#2e2e2e",
        "action-secondary-border": "#e1e1e1",
        "action-subtle-bg-hover": "#f2f2f2",
        "action-subtle-bg-active": "#ebebeb",
        "action-subtle-fg": "#484848",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#f8f8f8",
        "status-neutral-border": "#e1e1e1",
        "status-neutral-fg": "#484848",
        "impact-low": "#a4a4a4",
        "impact-track": "#e1e1e1",
        "focus-ring-offset": "#ffffff"
      },
      "dark": {
        "surface-canvas": "#040404",
        "surface-default": "#141414",
        "surface-sunken": "#0b0b0b",
        "surface-raised": "#1f1f1f",
        "surface-nav": "#0b0b0b",
        "surface-hover": "#1f1f1f",
        "surface-active": "#292929",
        "surface-disabled": "#0b0b0b",
        "surface-inverse": "#f2f2f2",
        "content-primary": "#f2f2f2",
        "content-secondary": "#bebebe",
        "content-muted": "#959595",
        "content-placeholder": "#959595",
        "content-disabled": "#636363",
        "content-decorative": "#808080",
        "content-inverse": "#0d0d0d",
        "border-subtle": "#242424",
        "border-default": "#2e2e2e",
        "border-strong": "#484848",
        "action-primary-bg": "#f2f2f2",
        "action-primary-bg-hover": "#ffffff",
        "action-primary-bg-active": "#e1e1e1",
        "action-primary-fg": "#0d0d0d",
        "action-secondary-bg": "#1f1f1f",
        "action-secondary-bg-hover": "#292929",
        "action-secondary-bg-active": "#0b0b0b",
        "action-secondary-fg": "#f2f2f2",
        "action-secondary-border": "#2e2e2e",
        "action-subtle-bg-hover": "#1f1f1f",
        "action-subtle-bg-active": "#292929",
        "action-subtle-fg": "#bebebe",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#1f1f1f",
        "status-neutral-border": "#2e2e2e",
        "status-neutral-fg": "#bebebe",
        "impact-low": "#808080",
        "impact-track": "#2e2e2e",
        "focus-ring-offset": "#141414"
      }
    },
    "warm": {
      "label": "Warm",
      "palette": {
        "n-0": "#ffffff",
        "n-25": "#fcfcfa",
        "n-50": "#faf8f6",
        "n-100": "#f4f2ef",
        "n-150": "#edebe7",
        "n-200": "#e4e1dd",
        "n-300": "#d0cdc9",
        "n-400": "#a8a49e",
        "n-500": "#847f79",
        "n-550": "#76716a",
        "n-600": "#67625c",
        "n-700": "#4c4741",
        "n-800": "#312d28",
        "n-850": "#27231e",
        "n-900": "#1d1a16",
        "n-950": "#100d09",
        "dark-void": "#060403",
        "dark-sunken": "#0d0b07",
        "dark-base": "#16130f",
        "dark-raised": "#221f1a",
        "dark-overlay": "#2c2823",
        "dark-text-hi": "#f3f1ef",
        "dark-text-mid": "#c0bdb9",
        "dark-text-lo": "#99948f"
      },
      "light": {
        "surface-canvas": "#f4f2ef",
        "surface-default": "#ffffff",
        "surface-sunken": "#faf8f6",
        "surface-raised": "#ffffff",
        "surface-nav": "#faf8f6",
        "surface-hover": "#f4f2ef",
        "surface-active": "#edebe7",
        "surface-disabled": "#f4f2ef",
        "surface-inverse": "#1d1a16",
        "content-primary": "#1d1a16",
        "content-secondary": "#4c4741",
        "content-muted": "#67625c",
        "content-placeholder": "#76716a",
        "content-disabled": "#a8a49e",
        "content-decorative": "#847f79",
        "content-inverse": "#ffffff",
        "border-subtle": "#edebe7",
        "border-default": "#e4e1dd",
        "border-strong": "#d0cdc9",
        "action-primary-bg": "#1d1a16",
        "action-primary-bg-hover": "#312d28",
        "action-primary-bg-active": "#100d09",
        "action-primary-fg": "#ffffff",
        "action-secondary-bg": "#ffffff",
        "action-secondary-bg-hover": "#faf8f6",
        "action-secondary-bg-active": "#edebe7",
        "action-secondary-fg": "#312d28",
        "action-secondary-border": "#e4e1dd",
        "action-subtle-bg-hover": "#f4f2ef",
        "action-subtle-bg-active": "#edebe7",
        "action-subtle-fg": "#4c4741",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#faf8f6",
        "status-neutral-border": "#e4e1dd",
        "status-neutral-fg": "#4c4741",
        "impact-low": "#a8a49e",
        "impact-track": "#e4e1dd",
        "focus-ring-offset": "#ffffff"
      },
      "dark": {
        "surface-canvas": "#060403",
        "surface-default": "#16130f",
        "surface-sunken": "#0d0b07",
        "surface-raised": "#221f1a",
        "surface-nav": "#0d0b07",
        "surface-hover": "#221f1a",
        "surface-active": "#2c2823",
        "surface-disabled": "#0d0b07",
        "surface-inverse": "#f4f2ef",
        "content-primary": "#f3f1ef",
        "content-secondary": "#c0bdb9",
        "content-muted": "#99948f",
        "content-placeholder": "#99948f",
        "content-disabled": "#67625c",
        "content-decorative": "#847f79",
        "content-inverse": "#100d09",
        "border-subtle": "#27231e",
        "border-default": "#312d28",
        "border-strong": "#4c4741",
        "action-primary-bg": "#f4f2ef",
        "action-primary-bg-hover": "#ffffff",
        "action-primary-bg-active": "#e4e1dd",
        "action-primary-fg": "#100d09",
        "action-secondary-bg": "#221f1a",
        "action-secondary-bg-hover": "#2c2823",
        "action-secondary-bg-active": "#0d0b07",
        "action-secondary-fg": "#f3f1ef",
        "action-secondary-border": "#312d28",
        "action-subtle-bg-hover": "#221f1a",
        "action-subtle-bg-active": "#2c2823",
        "action-subtle-fg": "#c0bdb9",
        "action-danger-fg": "#ffffff",
        "status-neutral-bg": "#221f1a",
        "status-neutral-border": "#312d28",
        "status-neutral-fg": "#c0bdb9",
        "impact-low": "#847f79",
        "impact-track": "#312d28",
        "focus-ring-offset": "#16130f"
      }
    }
  };

export const ACCENTS: Record<string, ProtoVariant> = {
    "teal": {
      "label": "Teal",
      "note": "60° from success, the nearest alarm colour",
      "palette": {
        "a-50": "#e5f5f8",
        "a-100": "#cfedf2",
        "a-200": "#acdbe3",
        "a-300": "#81c0cc",
        "a-400": "#4f99a6",
        "a-500": "#287b88",
        "a-600": "#0d636f",
        "a-700": "#094b55",
        "a-800": "#06373e",
        "a-900": "#022227"
      },
      "light": {
        "surface-selected": "#e5f5f8",
        "content-accent": "#0d636f",
        "border-accent": "#287b88",
        "status-info-bg": "#e5f5f8",
        "status-info-border": "#acdbe3",
        "status-info-fg": "#094b55",
        "focus-ring": "#287b88"
      },
      "dark": {
        "surface-selected": "#022227",
        "content-accent": "#81c0cc",
        "border-accent": "#287b88",
        "status-info-bg": "#022227",
        "status-info-border": "#06373e",
        "status-info-fg": "#acdbe3",
        "focus-ring": "#4f99a6"
      }
    },
    "indigo": {
      "label": "Indigo",
      "note": "112° from danger, the nearest alarm colour",
      "palette": {
        "a-50": "#eef1fe",
        "a-100": "#e0e5fc",
        "a-200": "#c7cff3",
        "a-300": "#a7b2df",
        "a-400": "#7e89bb",
        "a-500": "#616b9d",
        "a-600": "#4c5482",
        "a-700": "#393f63",
        "a-800": "#292e4a",
        "a-900": "#181b2f"
      },
      "light": {
        "surface-selected": "#eef1fe",
        "content-accent": "#4c5482",
        "border-accent": "#616b9d",
        "status-info-bg": "#eef1fe",
        "status-info-border": "#c7cff3",
        "status-info-fg": "#393f63",
        "focus-ring": "#616b9d"
      },
      "dark": {
        "surface-selected": "#181b2f",
        "content-accent": "#a7b2df",
        "border-accent": "#616b9d",
        "status-info-bg": "#181b2f",
        "status-info-border": "#292e4a",
        "status-info-fg": "#c7cff3",
        "focus-ring": "#7e89bb"
      }
    },
    "blue": {
      "label": "Blue",
      "note": "100° from success, the nearest alarm colour",
      "palette": {
        "a-50": "#e9f3fe",
        "a-100": "#d7e8fb",
        "a-200": "#b9d4f1",
        "a-300": "#95b8dd",
        "a-400": "#6890b9",
        "a-500": "#49729c",
        "a-600": "#355b81",
        "a-700": "#274562",
        "a-800": "#1c3249",
        "a-900": "#0e1e2e"
      },
      "light": {
        "surface-selected": "#e9f3fe",
        "content-accent": "#355b81",
        "border-accent": "#49729c",
        "status-info-bg": "#e9f3fe",
        "status-info-border": "#b9d4f1",
        "status-info-fg": "#274562",
        "focus-ring": "#49729c"
      },
      "dark": {
        "surface-selected": "#0e1e2e",
        "content-accent": "#95b8dd",
        "border-accent": "#49729c",
        "status-info-bg": "#0e1e2e",
        "status-info-border": "#1c3249",
        "status-info-fg": "#b9d4f1",
        "focus-ring": "#6890b9"
      }
    },
    "sky": {
      "label": "Sky",
      "note": "80° from success, the nearest alarm colour",
      "palette": {
        "a-50": "#e6f4fc",
        "a-100": "#d2ebf8",
        "a-200": "#b0d8ec",
        "a-300": "#88bdd7",
        "a-400": "#5995b2",
        "a-500": "#367794",
        "a-600": "#21607a",
        "a-700": "#18485d",
        "a-800": "#103545",
        "a-900": "#06202b"
      },
      "light": {
        "surface-selected": "#e6f4fc",
        "content-accent": "#21607a",
        "border-accent": "#367794",
        "status-info-bg": "#e6f4fc",
        "status-info-border": "#b0d8ec",
        "status-info-fg": "#18485d",
        "focus-ring": "#367794"
      },
      "dark": {
        "surface-selected": "#06202b",
        "content-accent": "#88bdd7",
        "border-accent": "#367794",
        "status-info-bg": "#06202b",
        "status-info-border": "#103545",
        "status-info-fg": "#b0d8ec",
        "focus-ring": "#5995b2"
      }
    },
    "cyan": {
      "label": "Cyan",
      "note": "45° from success, the nearest alarm colour",
      "palette": {
        "a-50": "#e5f6f5",
        "a-100": "#cfeded",
        "a-200": "#acdcdb",
        "a-300": "#81c2c1",
        "a-400": "#4e9b9a",
        "a-500": "#267d7d",
        "a-600": "#0a6565",
        "a-700": "#074c4d",
        "a-800": "#053838",
        "a-900": "#012222"
      },
      "light": {
        "surface-selected": "#e5f6f5",
        "content-accent": "#0a6565",
        "border-accent": "#267d7d",
        "status-info-bg": "#e5f6f5",
        "status-info-border": "#acdcdb",
        "status-info-fg": "#074c4d",
        "focus-ring": "#267d7d"
      },
      "dark": {
        "surface-selected": "#012222",
        "content-accent": "#81c2c1",
        "border-accent": "#267d7d",
        "status-info-bg": "#012222",
        "status-info-border": "#053838",
        "status-info-fg": "#acdcdb",
        "focus-ring": "#4e9b9a"
      }
    },
    "emerald": {
      "label": "Emerald",
      "note": "only 15° from success - a selected row will read as an alarm",
      "palette": {
        "a-50": "#e7f6ef",
        "a-100": "#d4ede1",
        "a-200": "#b3dcc9",
        "a-300": "#8dc2aa",
        "a-400": "#5d9b81",
        "a-500": "#3c7d63",
        "a-600": "#27654d",
        "a-700": "#1c4d3a",
        "a-800": "#13382a",
        "a-900": "#082218"
      },
      "light": {
        "surface-selected": "#e7f6ef",
        "content-accent": "#27654d",
        "border-accent": "#3c7d63",
        "status-info-bg": "#e7f6ef",
        "status-info-border": "#b3dcc9",
        "status-info-fg": "#1c4d3a",
        "focus-ring": "#3c7d63"
      },
      "dark": {
        "surface-selected": "#082218",
        "content-accent": "#8dc2aa",
        "border-accent": "#3c7d63",
        "status-info-bg": "#082218",
        "status-info-border": "#13382a",
        "status-info-fg": "#b3dcc9",
        "focus-ring": "#5d9b81"
      }
    },
    "green": {
      "label": "Green",
      "note": "only 10° from success - a selected row will read as an alarm",
      "palette": {
        "a-50": "#ecf5ea",
        "a-100": "#dbecd8",
        "a-200": "#c0dabb",
        "a-300": "#9ebf97",
        "a-400": "#74986c",
        "a-500": "#557a4d",
        "a-600": "#406239",
        "a-700": "#304a2a",
        "a-800": "#22361e",
        "a-900": "#132110"
      },
      "light": {
        "surface-selected": "#ecf5ea",
        "content-accent": "#406239",
        "border-accent": "#557a4d",
        "status-info-bg": "#ecf5ea",
        "status-info-border": "#c0dabb",
        "status-info-fg": "#304a2a",
        "focus-ring": "#557a4d"
      },
      "dark": {
        "surface-selected": "#132110",
        "content-accent": "#9ebf97",
        "border-accent": "#557a4d",
        "status-info-bg": "#132110",
        "status-info-border": "#22361e",
        "status-info-fg": "#c0dabb",
        "focus-ring": "#74986c"
      }
    },
    "lime": {
      "label": "Lime",
      "note": "only 30° from success - a selected row will read as an alarm",
      "palette": {
        "a-50": "#f0f4e7",
        "a-100": "#e3ead2",
        "a-200": "#ccd6b2",
        "a-300": "#aebb8c",
        "a-400": "#86935e",
        "a-500": "#69763e",
        "a-600": "#535e2b",
        "a-700": "#3e471f",
        "a-800": "#2d3415",
        "a-900": "#1b1f0a"
      },
      "light": {
        "surface-selected": "#f0f4e7",
        "content-accent": "#535e2b",
        "border-accent": "#69763e",
        "status-info-bg": "#f0f4e7",
        "status-info-border": "#ccd6b2",
        "status-info-fg": "#3e471f",
        "focus-ring": "#69763e"
      },
      "dark": {
        "surface-selected": "#1b1f0a",
        "content-accent": "#aebb8c",
        "border-accent": "#69763e",
        "status-info-bg": "#1b1f0a",
        "status-info-border": "#2d3415",
        "status-info-fg": "#ccd6b2",
        "focus-ring": "#86935e"
      }
    },
    "amber": {
      "label": "Amber",
      "note": "only 5° from warning - a selected row will read as an alarm",
      "palette": {
        "a-50": "#f9f0e5",
        "a-100": "#f3e4cf",
        "a-200": "#e5cdad",
        "a-300": "#cdaf85",
        "a-400": "#a78657",
        "a-500": "#8a6836",
        "a-600": "#715122",
        "a-700": "#563d19",
        "a-800": "#3f2c10",
        "a-900": "#271a07"
      },
      "light": {
        "surface-selected": "#f9f0e5",
        "content-accent": "#715122",
        "border-accent": "#8a6836",
        "status-info-bg": "#f9f0e5",
        "status-info-border": "#e5cdad",
        "status-info-fg": "#563d19",
        "focus-ring": "#8a6836"
      },
      "dark": {
        "surface-selected": "#271a07",
        "content-accent": "#cdaf85",
        "border-accent": "#8a6836",
        "status-info-bg": "#271a07",
        "status-info-border": "#3f2c10",
        "status-info-fg": "#e5cdad",
        "focus-ring": "#a78657"
      }
    },
    "orange": {
      "label": "Orange",
      "note": "only 20° from warning - a selected row will read as an alarm",
      "palette": {
        "a-50": "#fdefe7",
        "a-100": "#f9e1d4",
        "a-200": "#edc8b4",
        "a-300": "#d8a98f",
        "a-400": "#b27f62",
        "a-500": "#946043",
        "a-600": "#7a4b2f",
        "a-700": "#5d3823",
        "a-800": "#452818",
        "a-900": "#2b170c"
      },
      "light": {
        "surface-selected": "#fdefe7",
        "content-accent": "#7a4b2f",
        "border-accent": "#946043",
        "status-info-bg": "#fdefe7",
        "status-info-border": "#edc8b4",
        "status-info-fg": "#5d3823",
        "focus-ring": "#946043"
      },
      "dark": {
        "surface-selected": "#2b170c",
        "content-accent": "#d8a98f",
        "border-accent": "#946043",
        "status-info-bg": "#2b170c",
        "status-info-border": "#452818",
        "status-info-fg": "#edc8b4",
        "focus-ring": "#b27f62"
      }
    },
    "rose": {
      "label": "Rose",
      "note": "only 12° from danger - a selected row will read as an alarm",
      "palette": {
        "a-50": "#feedee",
        "a-100": "#fbdedf",
        "a-200": "#f0c4c6",
        "a-300": "#dba4a7",
        "a-400": "#b6797d",
        "a-500": "#975b60",
        "a-600": "#7d454a",
        "a-700": "#5f3438",
        "a-800": "#462528",
        "a-900": "#2c1517"
      },
      "light": {
        "surface-selected": "#feedee",
        "content-accent": "#7d454a",
        "border-accent": "#975b60",
        "status-info-bg": "#feedee",
        "status-info-border": "#f0c4c6",
        "status-info-fg": "#5f3438",
        "focus-ring": "#975b60"
      },
      "dark": {
        "surface-selected": "#2c1517",
        "content-accent": "#dba4a7",
        "border-accent": "#975b60",
        "status-info-bg": "#2c1517",
        "status-info-border": "#462528",
        "status-info-fg": "#f0c4c6",
        "focus-ring": "#b6797d"
      }
    },
    "magenta": {
      "label": "Magenta",
      "note": "47° from danger, the nearest alarm colour",
      "palette": {
        "a-50": "#fbedf6",
        "a-100": "#f6deed",
        "a-200": "#e9c5db",
        "a-300": "#d2a4c2",
        "a-400": "#ac7a9b",
        "a-500": "#8e5c7d",
        "a-600": "#744765",
        "a-700": "#58354d",
        "a-800": "#412638",
        "a-900": "#291622"
      },
      "light": {
        "surface-selected": "#fbedf6",
        "content-accent": "#744765",
        "border-accent": "#8e5c7d",
        "status-info-bg": "#fbedf6",
        "status-info-border": "#e9c5db",
        "status-info-fg": "#58354d",
        "focus-ring": "#8e5c7d"
      },
      "dark": {
        "surface-selected": "#291622",
        "content-accent": "#d2a4c2",
        "border-accent": "#8e5c7d",
        "status-info-bg": "#291622",
        "status-info-border": "#412638",
        "status-info-fg": "#e9c5db",
        "focus-ring": "#ac7a9b"
      }
    },
    "violet": {
      "label": "Violet",
      "note": "87° from danger, the nearest alarm colour",
      "palette": {
        "a-50": "#f3effc",
        "a-100": "#e9e2f9",
        "a-200": "#d6caee",
        "a-300": "#baabd9",
        "a-400": "#9382b4",
        "a-500": "#766496",
        "a-600": "#5f4e7c",
        "a-700": "#473a5f",
        "a-800": "#342a46",
        "a-900": "#20192c"
      },
      "light": {
        "surface-selected": "#f3effc",
        "content-accent": "#5f4e7c",
        "border-accent": "#766496",
        "status-info-bg": "#f3effc",
        "status-info-border": "#d6caee",
        "status-info-fg": "#473a5f",
        "focus-ring": "#766496"
      },
      "dark": {
        "surface-selected": "#20192c",
        "content-accent": "#baabd9",
        "border-accent": "#766496",
        "status-info-bg": "#20192c",
        "status-info-border": "#342a46",
        "status-info-fg": "#d6caee",
        "focus-ring": "#9382b4"
      }
    }
  };

export const FONTS: Record<string, ProtoFont> = {
    "plex": {
      "label": "Graphite",
      "note": "the shipped voice: one family doing every job, no contrast anywhere",
      "sans": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "mono": "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "display": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "prose": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "tag": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "num": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "displayWeight": 600,
      "displayTracking": "-0.011em",
      "tagCase": "none",
      "tagTracking": "var(--m-tracking-normal)",
      "tagSize": "var(--m-text-xs)",
      "tagWeight": 400
    },
    "swiss": {
      "label": "Swiss",
      "note": "Linear: one grotesque, headings pulled tight, tags as small caps",
      "sans": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "mono": "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "display": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "prose": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "tag": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "num": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "displayWeight": 600,
      "displayTracking": "-0.028em",
      "tagCase": "uppercase",
      "tagTracking": "0.075em",
      "tagSize": "0.625rem",
      "tagWeight": 600
    },
    "console": {
      "label": "Console",
      "note": "Vercel: sans interface, and every figure and tag in the mono",
      "sans": "'Geist', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "mono": "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "display": "'Geist', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "prose": "'Geist', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "tag": "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "num": "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "displayWeight": 600,
      "displayTracking": "-0.032em",
      "tagCase": "uppercase",
      "tagTracking": "0.04em",
      "tagSize": "0.625rem",
      "tagWeight": 500
    },
    "editorial": {
      "label": "Editorial",
      "note": "Notion: a text serif on the page title and the writing, sans rows",
      "sans": "'Source Sans 3', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "mono": "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      "display": "'Source Serif 4', Georgia, 'Times New Roman', serif",
      "prose": "'Source Serif 4', Georgia, 'Times New Roman', serif",
      "tag": "'Source Sans 3', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "num": "'Source Sans 3', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      "displayWeight": 600,
      "displayTracking": "-0.012em",
      "tagCase": "none",
      "tagTracking": "var(--m-tracking-normal)",
      "tagSize": "var(--m-text-xs)",
      "tagWeight": 400
    },
    "system": {
      "label": "System",
      "note": "GitHub: the OS’s own face, a size up, nothing loaded, nothing foreign",
      "sans": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      "mono": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
      "display": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      "prose": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      "tag": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      "num": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
      "displayWeight": 600,
      "displayTracking": "-0.021em",
      "tagCase": "none",
      "tagTracking": "var(--m-tracking-normal)",
      "tagSize": "var(--m-text-xs)",
      "tagWeight": 400
    }
  };

/** The three corner shapes, as antd needs them: numbers, because it computes
 *  inner corners from them and cannot read a custom property. */
export interface ProtoCorners {
  label: string;
  note: string;
  chip: number;
  control: number;
  surface: number;
  /** capped: a checkbox must never become a circle */
  check: number;
}

export const CORNERS: Record<string, ProtoCorners> = {
    "sharp": {
      "label": "Sharp",
      "note": "drawn with a ruler",
      "chip": 0,
      "control": 2,
      "surface": 4,
      "check": 0
    },
    "soft": {
      "label": "Soft",
      "note": "the shipped shape",
      "chip": 2,
      "control": 4,
      "surface": 8,
      "check": 2
    },
    "round": {
      "label": "Round",
      "note": "pills and soft boxes",
      "chip": 999,
      "control": 10,
      "surface": 16,
      "check": 4
    }
  };

export const DEFAULTS = { grey: 'cool', accent: 'teal', font: 'plex', density: 'compact', corners: 'soft', filters: 'outline', trigger: 'button' } as const;

export type GreyKey = keyof typeof GREYS;
export type AccentKey = keyof typeof ACCENTS;
export type FontKey = keyof typeof FONTS;
export type DensityKey = 'compact' | 'spaced';
export type CornersKey = keyof typeof CORNERS;
